steps:
  # Build Backend
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["build", "-t", "gcr.io/$PROJECT_ID/backend", "./backend"]

  # Build Frontend
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend", "./frontend2"]

  # Push images
  # - name: "gcr.io/cloud-builders/docker"
  #   args: ["push", "gcr.io/$PROJECT_ID/backend"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/frontend"]

  # Deploy to Cloud Run
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "run"
  #     - "deploy"
  #     - "backend"
  #     - "--image"
  #     - "gcr.io/$PROJECT_ID/backend"
  #     - "--region"
  #     - "us-central1"
  #     - "--platform"
  #     - "managed"
  #     - "--allow-unauthenticated"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "frontend"
      - "--image"
      - "gcr.io/$PROJECT_ID/frontend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

# Add logging configuration
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/backend"
  - "gcr.io/$PROJECT_ID/frontend"
